### ISSUE TITLE
About execution of this repo

### ISSUE THREAD

**Issue by gokcan** [sonmezonur/crud-go-redis#1]
Hi Onur,

How can we execute this example and make it work in our environment after cloning the repo.

**Comment by sonmezonur** [comment]
Hi Gokcan,

I updated documentation in detail by considering your referral. I hope testing, deployment and usage can be easily tracked by after these commits.

8e6e9d07f96e335e24f9a65ff4c5b8ec3b61adba
f058413d5d1375c8a5c171c0aa4b657c5697d6ea
